# @summary Possible keys for the [Manager] section of a system.conf/user.conf drop-in file
# @see https://www.freedesktop.org/software/systemd/man/latest/systemd-system.conf.html
type Systemd::Unit::Manager = Struct[
  # lint:ignore:140chars
  {
    Optional['LogLevel'] => Systemd::LogLevel,
    Optional['LogTarget'] => Enum['console','console-prefixed','kmsg','journal','journal-or-kmsg','auto','null'],
    Optional['LogColor'] => Systemd::Boolean,
    Optional['LogLocation'] => Systemd::Boolean,
    Optional['LogTime'] => Systemd::Boolean,
    Optional['DumpCore'] => Systemd::Boolean,
    Optional['ShowStatus'] => Variant[Systemd::Boolean, Enum['auto','error']],
    Optional['CrashChangeVT'] => Variant[Systemd::Boolean, Integer[1,63]],
    Optional['CrashShell'] => Systemd::Boolean,
    Optional['CrashReboot'] => Systemd::Boolean, # Obsoleted by CrashAction in v256, delete after Debian 12 EOL
    Optional['CrashAction'] => Enum['freeze', 'reboot', 'poweroff'],
    Optional['CtrlAltDelBurstAction'] => Enum['reboot-force','poweroff-force','reboot-immediate','poweroff-immediate','none'],
    Optional['CPUAffinity'] => Variant[Enum['numa'], Pattern['^[0-9, -]+$']],
    Optional['NUMAPolicy'] => Enum['default','preferred','bind','interleave','local'],
    Optional['NUMAMask'] => Variant[Enum['all'], Pattern['^[0-9, -]+$']],
    Optional['RuntimeWatchdogSec'] => Variant[Enum['off','default'], Systemd::Timespan],
    Optional['RuntimeWatchdogPreSec'] => Variant[Enum['off'], Systemd::Timespan],
    Optional['RuntimeWatchdogPreGovernor'] => Variant[Enum['noop', 'panic'], String[1]],
    Optional['RebootWatchdogSec'] => Variant[Enum['off','default'], Systemd::Timespan],
    Optional['KExecWatchdogSec'] => Variant[Enum['off','default'], Systemd::Timespan],
    Optional['WatchdogDevice'] => Stdlib::Absolutepath,
    Optional['CapabilityBoundingSet'] => Systemd::Capabilities,
    Optional['NoNewPrivileges'] => Systemd::Boolean,
    Optional['ProtectSystem'] => Variant[Enum['auto'], Systemd::Boolean],
    Optional['SystemCallArchitectures'] => String[1],
    Optional['TimerSlackNSec'] => Systemd::Timespan,
    Optional['StatusUnitFormat'] => Enum['combined','description','name'],
    Optional['DefaultTimerAccuracySec'] => Systemd::Timespan,
    Optional['DefaultStandardOutput'] => Systemd::Output,
    Optional['DefaultStandardError'] => Systemd::Output,
    Optional['DefaultTimeoutStartSec'] => Systemd::Timespan,
    Optional['DefaultTimeoutStopSec'] => Systemd::Timespan,
    Optional['DefaultTimeoutAbortSec'] => Systemd::Timespan,
    Optional['DefaultDeviceTimeoutSec'] => Systemd::Timespan,
    Optional['DefaultRestartSec'] => Systemd::Timespan,
    Optional['DefaultStartLimitIntervalSec'] => Variant[Enum['infinity'], Systemd::Timespan],
    Optional['DefaultStartLimitBurst'] => Integer[0],
    Optional['DefaultEnvironment'] => String,
    Optional['ManagerEnvironment'] => String,
    Optional['DefaultCPUAccounting'] => Systemd::Boolean,
    Optional['DefaultIOAccounting'] => Systemd::Boolean,
    Optional['DefaultIPAccounting'] => Systemd::Boolean,
    Optional['DefaultMemoryAccounting'] => Systemd::Boolean,
    Optional['DefaultTasksAccounting'] => Systemd::Boolean,
    Optional['DefaultTasksMax'] => Variant[Enum['infinity'], Integer[0], Systemd::Unit::Percent],
    Optional['DefaultLimitCPU'] => Variant[Enum['infinity'], Pattern['^\d+(s|m|h|d|w|M|y)?(:\d+(s|m|h|d|w|M|y)?)?$']],
    Optional['DefaultLimitFSIZE'] => Pattern['^(infinity|((\d+(K|M|G|T|P|E)?(:\d+(K|M|G|T|P|E)?)?)))$'],
    Optional['DefaultLimitDATA'] => Pattern['^(infinity|((\d+(K|M|G|T|P|E)?(:\d+(K|M|G|T|P|E)?)?)))$'],
    Optional['DefaultLimitSTACK'] => Pattern['^(infinity|((\d+(K|M|G|T|P|E)?(:\d+(K|M|G|T|P|E)?)?)))$'],
    Optional['DefaultLimitCORE'] => Pattern['^(infinity|((\d+(K|M|G|T|P|E)?(:\d+(K|M|G|T|P|E)?)?)))$'],
    Optional['DefaultLimitRSS'] => Pattern['^(infinity|((\d+(K|M|G|T|P|E)?(:\d+(K|M|G|T|P|E)?)?)))$'],
    Optional['DefaultLimitNOFILE'] => Variant[Integer[-1], Pattern['^(infinity|\d+(:(infinity|\d+))?)$']],
    Optional['DefaultLimitAS'] => Pattern['^(infinity|((\d+(K|M|G|T|P|E)?(:\d+(K|M|G|T|P|E)?)?)))$'],
    Optional['DefaultLimitNPROC'] => Variant[Integer[-1],Pattern['^(infinity|\d+(:(infinity|\d+))?)$']],
    Optional['DefaultLimitMEMLOCK'] => Pattern['^(infinity|((\d+(K|M|G|T|P|E)?(:\d+(K|M|G|T|P|E)?)?)))$'],
    Optional['DefaultLimitLOCKS'] => Integer[1],
    Optional['DefaultLimitSIGPENDING'] => Integer[1],
    Optional['DefaultLimitMSGQUEUE'] => Pattern['^(infinity|((\d+(K|M|G|T|P|E)?(:\d+(K|M|G|T|P|E)?)?)))$'],
    Optional['DefaultLimitNICE'] => Variant[Integer[0,40], Pattern['^(-\+([0-1]?[0-9]|20))|([0-3]?[0-9]|40)$']],
    Optional['DefaultLimitRTPRIO'] => Integer[0],
    Optional['DefaultLimitRTTIME'] => Pattern['^\d+(ms|s|m|h|d|w|M|y)?(:\d+(ms|s|m|h|d|w|M|y)?)?$'],
    Optional['DefaultOOMPolicy'] => Enum['continue', 'stop','kill'],
    Optional['DefaultOOMScoreAdjust'] => Integer[-1000,1000],
    Optional['DefaultSmackProcessLabel'] => String,
    Optional['ReloadLimitIntervalSec'] => Variant[Enum['infinity'], Systemd::Timespan],
    Optional['ReloadLimitBurst'] => Integer[0],
  }
  # lint:endignore
]
